---
- hosts: all
  tasks:
  - name: enable epel release repo
    yum:
     name: epel-release
     state: present
  - name: install python-pip
    yum:
     name: python-pip
     state: present
  - name: install virtualenv with pip
    shell: pip install virtualenv
  - name: create directory for virtualenv
    shell: mkdir /opt/cloudbreak_salt_env
  - name: create virtualenv enviornment
    shell: virtualenv /opt/cloudbreak_salt_env
  - name: install the 'Development tools' package group
    yum:
     name: "@Development tools"
     state: present
  - name: install salt dependencies
    yum:
     name: "{{ packages }}"
    vars:
     packages:
      - gcc
      - gcc-c++
      - autoconf
      - automake
      - zeromq-devel
      - python-devel
  - name: install salt
    shell: source /opt/cloudbreak_salt_env/bin/activate && pip install salt==2017.7.6
  - name: create salt configs
    shell: |
      mkdir /etc/salt && touch /etc/salt/master && touch /etc/salt/minion && echo 'master: 192.168.50.10' >> /etc/salt/minion
      cp /vagrant/salt-master.service /usr/lib/systemd/system/salt-master.service
      cp /vagrant/salt-minion.service /usr/lib/systemd/system/salt-minion.service
      cp /vagrant/salt-api.service /usr/lib/systemd/system/salt-api.service

- hosts: master
  tasks:
  - name: run salt-master
    shell: |
      systemctl start salt-master
#      source /opt/cloudbreak_salt_env/bin/activate && salt-key -A -y

- hosts: minion1, minion2
  tasks:
  - name: run salt-minion
    shell: systemctl start salt-minion
