---
- name: Add the user 'johnd' with a primary group of 'admin'
  user:
    name: saltuser
    comment: saltuser
    password: $6$fQ4y018Y3NvmvCQZ$kUdbbKx8LZq/J7wWYVOAYFFy96tuLlJLoL9CP1nTlPe6wc.Lp6TbQDmkqagNy7qVSnpvafv1cQaAqOgV3iC6f.
    #saltuser
    group: root
- name: enable epel release repo
  yum:
   name: epel-release
   state: present
- name: install salt dependencies including python-pip
  yum:
   name: "{{ packages }}"
  vars:
   packages:
    - "@Development tools"
    - python-pip
    - python-devel
- name: install virtualenv with pip
  shell: pip install virtualenv
- name: create directory for virtualenv
  file:
   path: /opt/salt_{{ salt_version }}
   state: directory
- name: create virtualenv environment
  shell: virtualenv /opt/salt_{{ salt_version }}
- name: install zeromq and salt
  shell: |
    source /opt/salt_{{ salt_version }}/bin/activate
    pip install pyzmq=={{ pyzmq_version }}
    pip install CherryPy
    pip install PyOpenSSL
    pip install salt=={{ salt_version }}
- name: create salt config directory
  file:
   path: /etc/salt
   state: directory
- name: disable zeromq and salt to install with yum package manager
  shell: echo "exclude=zeromq zeromq-devel salt" >> /etc/yum.conf
