---
- name: create salt master config
  file:
    path: /etc/salt/master
    state: touch
- name: add log destination to master config
  copy:
    content: "log_file: /opt/salt_{{ salt_version }}/log/salt/master\nlog_level: debug\n"
    dest: /etc/salt/master
- name: salt master service template copy
  template:
    src: salt-service-template.j2
    dest: /usr/lib/systemd/system/salt-master.service
  vars:
    service_description: "Salt Master"
    salt_component_name: salt-master
- name: salt api service template copy
  template:
    src: salt-service-template.j2
    dest: /usr/lib/systemd/system/salt-api.service
  vars:
    service_description: "Salt API"
    salt_component_name: salt-api
- name: run salt-master
  shell: |
    systemctl start salt-master
    systemctl enable salt-master.service
    systemctl start salt-api
    systemctl enable salt-api.service
