---
- name: create salt minion config
  file:
    path: /etc/salt/minion
    state: touch
- name: add master address and log destination to minion config
  copy:
    content: "master: 192.168.50.10\nlog_file: /opt/salt_{{ salt_version }}/log/salt/minion\nlog_level: debug\n"
    dest: /etc/salt/minion
- name: salt minion service template copy
  template:
    src: salt-service-template.j2
    dest: /usr/lib/systemd/system/salt-minion.service
  vars:
    service_description: "Salt Minion"
    salt_component_name: salt-minion
- name: run salt-minion
  shell: |
    systemctl start salt-minion
    systemctl enable salt-minion.service
