--- 
- name: salt minion config template copy
  template:
    src: minion.j2
    dest: /etc/salt/minion
  vars:
    master_ip: 192.168.50.10
- name: salt minion service template copy
  template:
    src: salt-service-template.j2
    dest: /usr/lib/systemd/system/salt-minion.service
  vars:
    service_description: "Salt Minion"
    salt_component_name: salt-minion
- name: run salt-minion
  shell: |
    systemctl start salt-minion
    systemctl enable salt-minion.service
